image: node:16.14.2
pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
      - src
  only:
    - main
